version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: build-env
    working_dir: /go/src/github.com
    environment:
      - USER=$USER
    volumes:
      - .:/go/src/github.com:cached
    tty: true
  executor:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: build-env
