name: Test

on:
  push:
    branches:
    - master
  pull_request:

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install docker-compose
        if: ${{ env.ACT }}
        run: |
          apt-get update && apt-get install -y docker docker-compose

      - name: Build containers
        run: docker-compose build app

      - name: Test
        run: |
          docker-compose run app /bin/bash -c "cd greetings && make"

